[package]
name = "telegram_files_cache_server"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "prisma-cli"
]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"

prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.10", default-features = false, features = ["postgresql"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
reqwest = { version = "0.11.22", features = ["json", "stream", "multipart"] }

tokio = { version = "1.34.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["compat"] }
axum = { version = "0.6.20", features = ["json"] }
axum-prometheus = "0.4.0"
chrono = "0.4.31"
sentry = { version = "0.31.8", features = ["debug-images"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}
tower-http = { version = "0.4.4", features = ["trace"] }

base64 = "0.21.5"

futures = "0.3.29"
futures-core = "0.3.29"
async-stream = "0.3.5"

minio-rsc = "0.2.0"
tempfile = "3.8.1"
bytes = "1.5.0"
