[package]
name = "telegram_files_cache_server"
version = "0.1.0"
edition = "2021"


[workspace]
members = [
    "prisma-cli"
]


[dependencies]
once_cell = "1.19.0"

dotenv = "0.15.0"

prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.10", default-features = false, features = ["postgresql"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
reqwest = { version = "0.12.4", features = ["json", "stream", "multipart"] }

tokio = { version = "1.37.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["compat"] }
axum = { version = "0.7.5", features = ["json"] }
axum-prometheus = "0.6.1"
chrono = "0.4.38"
sentry = { version = "0.32.3", features = ["debug-images"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}
sentry-tracing = "0.32.3"
tower-http = { version = "0.5.2", features = ["trace"] }

base64 = "0.22.0"

futures = "0.3.30"
futures-core = "0.3.30"
async-stream = "0.3.5"

minio-rsc = "0.2.2"
tempfile = "3.10.1"
bytes = "1.6.0"

teloxide = { version = "0.12.2", features = ["macros", "webhooks-axum", "cache-me", "throttle"] }

moka = { version = "0.12.7", features = ["future"] }
